### PR TITLE
Album Artwork

### LINKED ISSUE #16: Use error_chain
It adds backtraces. https://docs.rs/error-chain/0.11.0/error_chain/

### LINKED ISSUE #22: Embed Migrations
Use `embed_migrations` to automagically create/update a database if it doesn't exist.

### PR DESCRIPTION
**Pull request by 0xcaff**
Closes #22 
Closes #16 

Album artwork is imported, but not the the specification outlined in the wiki.

### CODE REVIEW

**Comment by Mcat12** [comment]
There are more issues that this closes:

Closes #29
Closes #28

**Comment by Mcat12** [comment]
I'm not sure if this caused it, but there are many `database is locked` errors in the tests.

File: src/bin/sync.rs [hunk 1]
```diff
@@ -45,37 +34,23 @@ error_chain! {
...
         .into_iter()
         .filter_map(|d| d.ok())
         .filter(|entry| {
             let path = entry.path();
-            let extension = path.extension().and_then(|e| e.to_str());
-            match extension {
-                Some(extension) if FORMAT_EXTENSIONS.contains(&extension) => true,
-                _ => false,
-            }
+            path.extension()
```
Comment (Mcat12) [inline src/bin/sync.rs]: Combine `entry` and `path` to avoid shadowing the original `path`:
```rust
entry
    .path()
    .extension()
[...]
```

File: src/import/song.rs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+        artist
+            .clone()
+            .or(album_artist.clone())
+            .ok_or(errors::ErrorKind::NoArtistError)?,
+        album_artist
+            .or(artist)
+            .ok_or(errors::ErrorKind::NoArtistError)?,
+    );
+
+    let album_name = props.album.as_ref().ok_or(errors::ErrorKind::NoAlbumError)?;
```
Comment (Mcat12) [inline src/import/song.rs]: This can probably happen as part of `add_or_get_album` so that you don't pass in more than you need. You only need to pass in the song properties, not the album name and year as well because you can already get those off of the song properties.

File: src/import/song.rs [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    let album = add_or_get_album(
+        path,
+        artwork_directory,
+        &props,
+        album_name,
+        album_artist.id,
+        props.year,
```
Comment (Mcat12) [inline src/import/song.rs]: No need to pass in the year again (it's already passed in as part of the song properties).

File: src/import/album.rs [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+
+fn find_artwork_in_dir(directory: &Path) -> io::Result<Option<PathBuf>> {
+    let images_iter = directory
+        .read_dir()?
+        .filter_map(|e| e.ok())
+        .filter_map(|file| {
+            let path = file.path();
+            let extension = path.extension()?.to_string_lossy().to_lowercase();
+
+            if path.is_file() && ["jpg", "jpeg", "png"].contains(&extension.as_str()) {
```
Comment (Mcat12) [inline src/import/album.rs]: The auto-generated JPEG file for one of my cover arts was `jpe`, which is not included in this list.

File: src/models/album.rs [hunk 5]
```diff
@@ -26,6 +26,16 @@ impl Album {
...
     }
 
+    pub fn get_artwork_url(id: &str) -> String {
+        format!("/files/artwork/{}/raw", id)
+    }
+
+    pub fn artwork_url(&self) -> Option<String> {
+        self.artwork_path
+            .as_ref()
+            .map(|_| Album::get_artwork_url(&self.id.to_string()))
```
Comment (Mcat12) [inline src/models/album.rs]: This can be simplified into:
```rust
if self.artwork_path.is_some() {
    Some(Album::get_artwork_url(&self.id.to_string()))
} else {
    None
}
```

File: src/bin/server.rs [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+    r.ok_or(IronError::new(
+        errors::Error::from(errors::ErrorKind::EmptyOption),
+        status,
+    ))
+}
+
+fn song_stream_handler(req: &mut Request) -> IronResult<Response> {
+    let ctx = GraphQLContext::from_request(req);
+    let ref id = convert_option(
+        req.extensions.get::<Router>().unwrap().find("id"),
```
[the remark this answers is not in the document]
Comment (0xcaff) [reply src/bin/server.rs]: The example in the docs unwrap. I'll just unwrap too.

File: src/bin/server.rs [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+
+use diesel::result::QueryResult;
+use std::ops::Deref;
+use std::path::Path;
+
+mod errors {
+    error_chain! {
+        errors {
+            EmptyOption {
+                description("the option was empty when it was expected to be non empty")
```
[the remark this answers is not in the document]
Comment (0xcaff) [reply src/bin/server.rs]: > This exposes implementation details 

Exposes implementation details to what? This error is never sent in the response or logged anywhere. It seems that iron just passes it to middleware.

File: src/models/album.rs [hunk 8]
```diff
@@ -26,6 +26,17 @@ impl Album {
         album::table.filter(album::id.eq(id)).first::<Self>(conn)
     }
 
+    pub fn get_artwork_url(id: &str) -> String {
+        format!("/files/artwork/{}/raw", id)
+    }
+
+    pub fn artwork_url(&self) -> Option<String> {
+        match self.artwork_path {
+            Some(..) => Some(Album::get_artwork_url(&self.id.to_string())),
```
Comment (Mcat12) [inline src/models/album.rs]: Why do you use `..` here instead of `_` like below?

Comment (0xcaff) [reply src/models/album.rs]: Because it looks cool.

File: src/import/artwork.rs [hunk 9]
```diff
@@ -0,0 +1,190 @@
...
+fn find_best_artwork<'a>(path: &Path, props: &'a SongProperties) -> Result<Option<ImageInfo<'a>>> {
+    let embedded_artwork = props
+        .cover_artwork
+        .as_ref()
+        .map_or(Ok(None), ImageInfo::from_embedded)?;
+
+    let mut linked_artwork = find_covers_in_path(path.parent().unwrap())?;
+
+    let mut all_artwork: Vec<ImageInfo> = vec![];
+    all_artwork.append(&mut linked_artwork);
```
[the remark this answers is not in the document]
Comment (Mcat12) [reply src/import/artwork.rs]: Your method copies data around for no reason. It starts with a vec and ends with the same vec.

[the remark this answers is not in the document]
Comment (Mcat12) [reply src/import/artwork.rs]: Also, the line is actually shorter both horizontally and vertically (3 lines vs 1).

[the remark this answers is not in the document]
Comment (0xcaff) [reply src/import/artwork.rs]: It moves the data. There are no copies.

[the remark this answers is not in the document]
Comment (Mcat12) [reply src/import/artwork.rs]: Then it should be a no brainer to change. You can replace 3 lines with 1
